# Site settings
title: NGR Electrical Ltd
email: ngrelectrical@gmail.com
description:
  NGR Electrical, Electricans London; 24 Hours a Day, Providing Installation,
  Maintenance and Emergency Electricans, all over London and the Southeast.
baseurl: ""
url: "http://ngrelectrical.co.uk"
twitter_username: NGR_Electrical
tel: 07706 367445

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]
