# Build settings
source: src
destination: dist

exclude: [
    "assets",
    "package.json",
    "node_modules",
    "bower.json",
    "bower_components",
    "gulpfile.js"
]

keep_files: [
    "assets/css/dist/ie.css",
    "assets/js/vendor",
]
